# Generated by Django 4.0.4 on 2022-10-09 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('a', 'Alumno'), ('d', 'Dae'), ('i', 'Informatico')], default='a', help_text='Tipo de usuario', max_length=1)),
                ('estado', models.CharField(choices=[('b', 'Bloqueado'), ('a', 'Activo')], default='a', help_text='Tipo de usuario', max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=9, null=True)),
                ('disabled', models.CharField(blank=True, default='false', max_length=5, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField(default=0)),
                ('horaIni', models.DateTimeField(blank=True, null=True)),
                ('horaTer', models.DateTimeField(blank=True, null=True)),
                ('evento', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.CharField(blank=True, choices=[('p', 'Pendiente'), ('a', 'Aprobada'), ('r', 'Rechazada')], default='p', help_text='Estado de la solicitud', max_length=1)),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('v', 'Vigente'), ('a', 'Aprobada'), ('c', 'Caducada')], default='v', help_text='Estado de la invitación', max_length=1)),
                ('invitado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.solicitud')),
            ],
        ),
    ]
