# Generated by Django 4.0.4 on 2022-10-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_solicitud_admin_id_alter_solicitud_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='mensaje',
            field=models.CharField(blank=True, default=' ', max_length=300, null=True),
        ),
    ]
