# Generated by Django 4.0.4 on 2022-10-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_solicitud_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='participantes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
