# Generated by Django 4.0.4 on 2022-10-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_solicitud_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('v', 'Vigente'), ('a', 'Aprobada'), ('r', 'Rechazada')], default='v', help_text='Estado de la invitación', max_length=1),
        ),
    ]
