# Generated by Django 4.0.4 on 2022-10-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_invitacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='clave',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
    ]
