# Generated by Django 4.1.2 on 2022-11-16 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_solicitud_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='invitado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
