# Generated by Django 4.1.2 on 2022-11-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_invitacion_invitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('v', 'Vigente'), ('a', 'Aprobada'), ('r', 'Rechazada'), ('c', 'Caducada')], default='v', help_text='Estado de la invitación', max_length=1),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(blank=True, choices=[('p', 'Pendiente'), ('a', 'Aprobada'), ('r', 'Rechazada'), ('c', 'Caducada')], default='p', help_text='Estado de la solicitud', max_length=1),
        ),
    ]
