# Generated by Django 4.1.2 on 2022-11-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_invitacion_estado_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='vigencia',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(blank=True, choices=[('p', 'Pendiente'), ('a', 'Aprobada'), ('r', 'Rechazada')], default='p', help_text='Estado de la solicitud', max_length=1),
        ),
    ]
