# Generated by Django 4.1.2 on 2022-11-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_solicitud_vigencia_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='vigencia',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
