# Generated by Django 4.1.2 on 2022-11-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_solicitud_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='vigencia',
            field=models.CharField(blank=True, default='True', max_length=10),
        ),
    ]
